server:
  port: 8086

eureka:
  #\u4E0D\u4ECE\u4E91\u7AEF\u62C9\u53D6eureka\u76F8\u5173\u670D\u52A1\u4FE1\u606F
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #\u901A\u8FC7ip\u5730\u5740\u7684\u65B9\u5F0F\u627E\u5BFB\u670D\u52A1
  instance:
    prefer-ip-address: true

spring:
  application:
    name: consumer-user

